// <auto-generated />
namespace RAD301S00151925Clubs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201610280841061_Initial Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
